name: .NET Core CI

on: [push, pull_request]

jobs:
  test:
    name: .Net Core ${{ matrix.framework }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        framework: ['2.1', '3.1']
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v2.2.0
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: ${{ matrix.framework }}
        
    - if: matrix.os == 'ubuntu-latest'
      name: Install libcurl
      run: |
       sudo apt update
       sudo apt install -y libcurl4
        
    - name: Tests
      run: dotnet test --framework netcoreapp${{ matrix.framework }}
